// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaBXkXdQucyqHGQCJWhcIhBRCCExdB1P8',
    appId: '1:673741025686:web:fd7d8db0820b41e1716db7',
    messagingSenderId: '673741025686',
    projectId: 'myapps-step',
    authDomain: 'myapps-step.firebaseapp.com',
    storageBucket: 'myapps-step.appspot.com',
    measurementId: 'G-88EYD50VKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_ceG13Py9u7yHJBkhVdISIeWW4kqJ5M',
    appId: '1:673741025686:android:e4375eba06e12491716db7',
    messagingSenderId: '673741025686',
    projectId: 'myapps-step',
    storageBucket: 'myapps-step.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQcoj0MYVHUj63rFYrhPNoCvobF1Bj_o',
    appId: '1:673741025686:ios:f314511c645188b4716db7',
    messagingSenderId: '673741025686',
    projectId: 'myapps-step',
    storageBucket: 'myapps-step.appspot.com',
    iosBundleId: 'com.example.architectDesignApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaBXkXdQucyqHGQCJWhcIhBRCCExdB1P8',
    appId: '1:673741025686:web:eb54d6adaa969ed0716db7',
    messagingSenderId: '673741025686',
    projectId: 'myapps-step',
    authDomain: 'myapps-step.firebaseapp.com',
    storageBucket: 'myapps-step.appspot.com',
    measurementId: 'G-2PGSJBMRFZ',
  );
}
